name: PHP Composer

on:
  push:
    paths: 
      - '/.github/workflows/mqtt-check/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer require bluerhinos/phpmqtt
        
    - name: Test MQTT
      run: php -v
