name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        working-directory: ./img/apache2rewrite
        run: docker build . --file Dockerfile --tag apache2rewrite:$(date +%s)
